insert into ville (id_ville, nom_ville) values (1, 'Kastornoye');
insert into ville (id_ville, nom_ville) values (2, 'Butere');
insert into ville (id_ville, nom_ville) values (3, 'Xiaoruo');
insert into ville (id_ville, nom_ville) values (4, 'Pinellas Park');
insert into ville (id_ville, nom_ville) values (5, 'Draginje');
insert into ville (id_ville, nom_ville) values (6, 'Ganjiangtou');
insert into ville (id_ville, nom_ville) values (7, 'Heping');
insert into ville (id_ville, nom_ville) values (8, 'Caringin');
insert into ville (id_ville, nom_ville) values (9, 'Philadelphia');
insert into ville (id_ville, nom_ville) values (10, 'Karnobat');
insert into ville (id_ville, nom_ville) values (11, 'Horton');
insert into ville (id_ville, nom_ville) values (12, 'Poigar');
insert into ville (id_ville, nom_ville) values (13, 'Mežica');
insert into ville (id_ville, nom_ville) values (14, 'Fonte do Feto');
insert into ville (id_ville, nom_ville) values (15, 'Huai Yot');
insert into ville (id_ville, nom_ville) values (16, 'Jeziorzany');
insert into ville (id_ville, nom_ville) values (17, 'Dagu');
insert into ville (id_ville, nom_ville) values (18, 'HanHuang');
insert into ville (id_ville, nom_ville) values (19, 'Kochenëvo');
insert into ville (id_ville, nom_ville) values (20, 'Raposeira');
insert into ville (id_ville, nom_ville) values (21, 'Hongguang');
insert into ville (id_ville, nom_ville) values (22, 'Changshan');
insert into ville (id_ville, nom_ville) values (23, 'Banjar Bau Kawan');
insert into ville (id_ville, nom_ville) values (24, 'Varėna');
insert into ville (id_ville, nom_ville) values (25, 'Gŭlŭbovo');
insert into ville (id_ville, nom_ville) values (26, 'Velká Dobrá');
insert into ville (id_ville, nom_ville) values (27, 'Zvole');
insert into ville (id_ville, nom_ville) values (28, 'Levallois_Perret');
insert into ville (id_ville, nom_ville) values (29, 'Casal');
insert into ville (id_ville, nom_ville) values (30, 'Stýpsi');
insert into ville (id_ville, nom_ville) values (31, 'Longtang');
insert into ville (id_ville, nom_ville) values (32, 'Årjäng');
insert into ville (id_ville, nom_ville) values (33, 'Hrastnik');
insert into ville (id_ville, nom_ville) values (34, 'Malakal');
insert into ville (id_ville, nom_ville) values (35, 'Londrina');
insert into ville (id_ville, nom_ville) values (36, 'Ninh Giang');
insert into ville (id_ville, nom_ville) values (37, 'Reims');
insert into ville (id_ville, nom_ville) values (38, 'Boise');
insert into ville (id_ville, nom_ville) values (39, 'Wielka Wieś');
insert into ville (id_ville, nom_ville) values (40, 'Lyon');
